## Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

**!!!Ссылка на архив с датасетами** http://files.grouplens.org/datasets/movielens/ml-25m.zip.

In [2]:
import pandas as pd

data_ratings = pd.read_csv('ratings.csv')
data_ratings.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [3]:
data_ratings[data_ratings.rating == 5.0]['movieId'].value_counts().to_csv('ratings_sorted.csv',header = False)
data_ratings_grouped = pd.read_csv('ratings_sorted.csv', names = ['movieId','number_of_5.0-scores'])
most_popular_movieId = data_ratings_grouped['movieId'][0]
data_movies = pd.read_csv('movies.csv')
data_movies[data_movies.movieId.isin([most_popular_movieId,])]

     movieId                             title       genres
314      318  Shawshank Redemption, The (1994)  Crime|Drama

## Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [5]:
dataset = pd.read_csv('power.csv')
dataset.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [6]:
dataset[ dataset['country'].str.contains('lat|lit|est', case=False) ]['country'].unique()

array(['Lithuania', 'Latvia', 'Estonia', 'State of Palestine',
       'Timor-Leste'], dtype=object)

In [7]:
dataset_country = dataset[dataset.country.isin(['Latvia','Lithuania','Estonia'])]
dataset_country_category = dataset_country[dataset_country.category.isin([4,12,21])]
dataset_country_category_year = dataset_country_category[(dataset_country_category.year >= 2005) & (dataset_country_category.year <= 2010)]
result = sum(dataset_country_category_year[dataset_country_category_year.quantity > 0]['quantity'])
print(f'Суммарное потребление стран Прибалтики категорий 4, 12 и 21 за период с 2005 по 2010 года: {result}')

Суммарное потребление стран Прибалтики категорий 4, 12 и 21 за период с 2005 по 2010 года: 240580.0

In [8]:
result = sum(dataset[dataset.country.isin(['Latvia','Lithuania','Estonia']) & dataset.category.isin([4,12,21]) \
        & (dataset.year >= 2005) & (dataset.year <= 2010) & (dataset.quantity > 0)]['quantity'])
print(f'Суммарное потребление стран Прибалтики категорий 4, 12 и 21 за период с 2005 по 2010 года: {result}')

Суммарное потребление стран Прибалтики категорий 4, 12 и 21 за период с 2005 по 2010 года: 240580.0

## Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц:

1. https://fortrader.org/quotes **(Не импортируется время. Вместо него NaN)**

1. https://www.finanz.ru/valyuty/v-realnom-vremeni **(Импортируется некорректно. Теряются разделители-запятые в значениях, спрос не считывается и т.д.)**
1. https://www.finam.ru/quotes/currencies/ **(Тоже так себе импортируется. Надо обрабатывать.)**

**Ссылка 1**

In [9]:
data = pd.read_html('https://fortrader.org/quotes', encoding='utf-8')
# len(data)
data[0]

,Название,Цена,Изменение,Изменение(%),Обновлено
0,EURRUB Курс евро к рублю сегодня,80.0977,0.2048,0.2563,NaN
1,USDRUB Курс рубля к доллару,73.4195,-0.1096,-0.1491,NaN

**Ссылка 2**

In [10]:
data = pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8')
# len(data)
data[1]

# page_url = 'https://www.finanz.ru/valyuty/v-realnom-vremeni'
# data = pd.read_html(page_url, attrs = {'class': 'quote_list'}, encoding='utf-8')
# len(data)
# data[0]

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,917007,-,930037,"-1,40 %",-13030,00:49:00
1,NaN,EUR/RUB,799130,-,815655,"-2,03 %",-16525,00:48:00
2,NaN,USD/RUB,736967,-,747945,"-1,47 %",-10978,00:47:00
3,NaN,JPY/RUB,06919,-,07003,"-1,21 %",-00085,00:49:00
4,NaN,CNY/RUB,104349,-,105857,"-1,42 %",-01508,00:47:00
5,NaN,CHF/RUB,757806,-,774172,"-2,11 %",-16367,00:48:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,10845,-,10904,"-0,54 %",-00059,00:47:00
8,NaN,EUR/GBP,08716,-,08764,"-0,55 %",-00048,00:48:00
9,NaN,EUR/JPY,1155750,-,1163800,"-0,69 %",-08050,00:48:00
10,NaN,EUR/CHF,10546,-,10530,"0,15 %",00016,00:47:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,09221,-,09173,"0,53 %",00048,00:47:00
13,NaN,USD/GBP,08037,-,08039,"-0,02 %",-00002,00:49:00
14,NaN,USD/JPY,1065750,-,1067590,"-0,17 %",-01840,00:48:00
15,NaN,USD/CHF,09727,-,09658,"0,71 %",00069,00:48:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),08700,-,08600,"0,74 %",00001,00:49:00
18,NaN,JPY/GBP,00075,-,00075,"0,19 %",00000,00:49:00
19,NaN,JPY/USD,00094,-,00094,"0,23 %",00000,00:49:00
20,NaN,JPY/CHF (100:1),09100,-,09000,"0,87 %",00001,00:47:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,12443,-,12440,"0,02 %",00003,00:47:00
23,NaN,GBP/JPY,1325404,-,1327982,"-0,19 %",-02579,00:49:00
24,NaN,GBP/EUR,11474,-,11411,"0,55 %",00063,00:47:00
25,NaN,GBP/CHF,12103,-,12013,"0,75 %",00090,00:47:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,12103,-,12013,"0,75 %",00090,00:47:00
28,NaN,EUR/CHF,10546,-,10530,"0,15 %",00016,00:47:00
29,NaN,JPY/CHF (100:1),09100,-,09000,"0,87 %",00001,00:47:00
30,NaN,USD/CHF,09727,-,09658,"0,71 %",00069,00:48:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,292484,-,293930,"-0,49 %",-01446,00:49:00
33,NaN,USD/UAH,269707,-,269623,"0,03 %",00084,00:47:00
34,NaN,CHF/UAH,277306,-,279200,"-0,68 %",-01894,00:48:00
35,NaN,GBP/UAH,335597,-,335411,"0,06 %",00185,00:49:00

**Ссылка 3**

In [11]:
data = pd.read_html('https://www.finam.ru/quotes/currencies/')
# len(data)
data[0]

,Unnamed: 0,Инструмент,Посл. сделка,% Изм. цены,Открытие,Макс.,Мин.,Закрытие,"Объем, шт.",Время обн.
0,NaN,Eur/Chf,1.0544 CHF,0.04%,1.0539,1.0545,1.0539,1.054000,NaN,06.05 01:06
1,NaN,Eur/Jpy,115.471 JPY,0%,115.4660,115.5300,115.4520,115.475000,NaN,06.05 01:06
2,NaN,Eur/Usd,1.084 $,0%,1.0842,1.0842,1.0835,1.084000,NaN,06.05 01:06
3,NaN,Usd/Chf,0.9727 CHF,0.03%,0.9721,0.9731,0.9721,0.972400,NaN,06.05 01:06
4,NaN,Gbp/Usd,1.2442 $,0.02%,1.2440,1.2443,1.2437,1.244000,NaN,06.05 01:06
5,NaN,Usd/Jpy,106.53 JPY,0%,106.5300,106.5600,106.4900,106.530000,NaN,06.05 01:06
6,NaN,Usd/Cad,1.4037 CAD,-0.05%,1.4044,1.4046,1.4040,1.404400,NaN,06.05 01:06
7,NaN,Aud/Nzd,1.0628 NZD,0.01%,1.0630,1.0634,1.0630,1.062700,NaN,06.05 01:06
8,NaN,Индекс доллара*,99.87 $,0.3%,99.5800,100.0700,99.3800,99.570000,NaN,05.05 23:59
9,NaN,Aud/Usd,0.6433 $,0.08%,0.6428,0.6436,0.6428,0.642800,NaN,06.05 01:06
10,NaN,AMDRUB курс ЦБ,0.15,-0.01%,NaN,NaN,NaN,0.150000,NaN,01.05 00:00
11,NaN,Aud/Cad,0.9032 CAD,0.03%,0.9025,0.9037,0.9025,0.902900,NaN,06.05 01:06
12,NaN,Aud/Chf,0.6258 CHF,0.13%,0.6250,0.6260,0.6250,0.625000,NaN,06.05 01:06
13,NaN,Aud/Dkk,4.4286 DKK,0.12%,4.4252,4.4293,4.4252,4.423100,NaN,06.05 01:06
14,NaN,Aud/Jpy,68.54 JPY,0.09%,68.4710,68.5590,68.4710,68.475000,NaN,06.05 01:06
15,NaN,Aud/Nok,6.6026 NOK,0.08%,6.5988,6.6026,6.5988,6.597500,NaN,06.05 01:06
16,NaN,Aud/Sek,6.3128 SEK,0.12%,6.3050,6.3202,6.3050,6.305100,NaN,06.05 01:06
17,NaN,Aud/Sgd,0.911 SGD,0.12%,0.9099,0.9112,0.9099,0.909900,NaN,06.05 01:06
18,NaN,AUDRUB курс ЦБ,47.58,-0.01%,NaN,NaN,NaN,48.120000,NaN,01.05 00:00
19,NaN,AZNRUB курс ЦБ,42.87,-0.01%,NaN,NaN,NaN,43.440000,NaN,01.05 00:00
20,NaN,BCH-USD,246.46 $,NaN,NaN,NaN,NaN,245.620000,NaN,06.05 01:06
21,NaN,BGNRUB курс ЦБ,40.44,-0.01%,NaN,NaN,NaN,40.950000,NaN,01.05 00:00
22,NaN,Bitcoin / Euro,8289.68,NaN,NaN,NaN,NaN,8271.520000,NaN,06.05 01:06
23,NaN,Bitcoin / U.S. dollar,8987.91,NaN,NaN,NaN,NaN,8954.700000,NaN,06.05 01:06
24,NaN,Bitcoin Cash / Bitcoin,NaN,NaN,NaN,NaN,NaN,0.027474,NaN,06.05 01:06
25,NaN,Bitcoin Cash / Euro,NaN,NaN,NaN,NaN,NaN,227.160000,NaN,06.05 01:06
26,NaN,Bitcoin Cash / U.S. dollar,248.01,NaN,NaN,NaN,NaN,246.580000,NaN,05.05 01:00
27,NaN,BKTRUB_TOM,39.26 ₽,0.41%,NaN,NaN,NaN,39.260000,NaN,25.06.14 18:36
28,NaN,BRLRUB курс ЦБ,13.63,0.02%,NaN,NaN,NaN,13.400000,NaN,01.05 00:00
29,NaN,BTC-EUR,8296.33 €,NaN,NaN,NaN,NaN,8281.010000,NaN,06.05 01:06