## Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

**!!!Ссылка на архив с датасетами** http://files.grouplens.org/datasets/movielens/ml-25m.zip.

In [32]:
import pandas as pd

data_ratings = pd.read_csv('ratings.csv')
data_ratings.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [33]:
# #Вариант 1
# data_ratings[data_ratings.rating == 5.0]['movieId'].value_counts().to_csv('ratings_sorted.csv',header = False)
# data_ratings_grouped = pd.read_csv('ratings_sorted.csv', names = ['movieId','number_of_5.0-scores'])
# most_popular_movieId = data_ratings_grouped['movieId'][0]
# data_movies = pd.read_csv('movies.csv')
# data_movies[data_movies.movieId.isin([most_popular_movieId,])]

#Вариант 2
data_ratings_grouped = data_ratings[data_ratings.rating == 5.0].groupby('movieId').count().sort_values(by='rating',ascending=False).reset_index()
most_popular_movieId = data_ratings_grouped['movieId'][0]
data_movies = pd.read_csv('movies.csv')
data_movies[data_movies.movieId.isin([most_popular_movieId,])]

     movieId                             title       genres
314      318  Shawshank Redemption, The (1994)  Crime|Drama

## Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [34]:
dataset = pd.read_csv('power.csv')
dataset.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [35]:
dataset[ dataset['country'].str.contains('lat|lit|est', case=False) ]['country'].unique()

array(['Lithuania', 'Latvia', 'Estonia', 'State of Palestine',
       'Timor-Leste'], dtype=object)

In [36]:
dataset_country = dataset[dataset.country.isin(['Latvia','Lithuania','Estonia'])]
dataset_country_category = dataset_country[dataset_country.category.isin([4,12,21])]
dataset_country_category_year = dataset_country_category[(dataset_country_category.year >= 2005) & (dataset_country_category.year <= 2010)]
result = sum(dataset_country_category_year[dataset_country_category_year.quantity > 0]['quantity'])
print(f'Суммарное потребление стран Прибалтики категорий 4, 12 и 21 за период с 2005 по 2010 года: {result}')

Суммарное потребление стран Прибалтики категорий 4, 12 и 21 за период с 2005 по 2010 года: 240580.0

In [37]:
result = sum(dataset[dataset.country.isin(['Latvia','Lithuania','Estonia']) & dataset.category.isin([4,12,21]) \
        & (dataset.year >= 2005) & (dataset.year <= 2010) & (dataset.quantity > 0)]['quantity'])
print(f'Суммарное потребление стран Прибалтики категорий 4, 12 и 21 за период с 2005 по 2010 года: {result}')

Суммарное потребление стран Прибалтики категорий 4, 12 и 21 за период с 2005 по 2010 года: 240580.0

## Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц:

1. https://fortrader.org/quotes **(Не импортируется время. Вместо него NaN)**

1. https://www.finanz.ru/valyuty/v-realnom-vremeni **(Импортируется некорректно. Теряются разделители-запятые в значениях, спрос не считывается и т.д.)**
1. https://www.finam.ru/quotes/currencies/ **(Тоже так себе импортируется. Надо обрабатывать.)**

**Ссылка 1**

In [38]:
data = pd.read_html('https://fortrader.org/quotes', encoding='utf-8')
# len(data)
data[0]

,Название,Цена,Изменение,Изменение(%),Обновлено
0,EURRUB Курс евро к рублю сегодня,80.0977,-0.3381,-0.4203,NaN
1,USDRUB Курс рубля к доллару,73.4195,-1.0365,-1.3921,NaN

**Ссылка 2**

In [39]:
data = pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8')
# len(data)
data[1]

# page_url = 'https://www.finanz.ru/valyuty/v-realnom-vremeni'
# data = pd.read_html(page_url, attrs = {'class': 'quote_list'}, encoding='utf-8')
# len(data)
# data[0]

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,913466,-,919405,"-0,65 %",-05939,21:07:00
1,NaN,EUR/RUB,799686,-,805670,"-0,74 %",-05984,21:06:00
2,NaN,USD/RUB,738552,-,745005,"-0,87 %",-06453,21:07:00
3,NaN,JPY/RUB,06950,-,07023,"-1,04 %",-00073,21:07:00
4,NaN,CNY/RUB,104246,-,104860,"-0,59 %",-00614,21:07:00
5,NaN,CHF/RUB,758657,-,764103,"-0,71 %",-05446,21:07:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,10827,-,10796,"0,29 %",00032,21:06:00
8,NaN,EUR/GBP,08753,-,08747,"0,08 %",00007,21:06:00
9,NaN,EUR/JPY,1150565,-,1145100,"0,48 %",05465,21:06:00
10,NaN,EUR/CHF,10541,-,10527,"0,14 %",00015,21:06:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,09236,-,09264,"-0,30 %",-00028,21:06:00
13,NaN,USD/GBP,08083,-,08103,"-0,24 %",-00020,21:07:00
14,NaN,USD/JPY,1062700,-,1060800,"0,18 %",01900,21:06:00
15,NaN,USD/CHF,09734,-,09753,"-0,19 %",-00019,21:06:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),08700,-,08700,"-0,49 %",00000,21:07:00
18,NaN,JPY/GBP,00076,-,00076,"-0,40 %",00000,21:07:00
19,NaN,JPY/USD,00094,-,00094,"-0,17 %",00000,21:07:00
20,NaN,JPY/CHF (100:1),09200,-,09200,"-0,34 %",00000,21:06:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,12370,-,12343,"0,22 %",00027,21:06:00
23,NaN,GBP/JPY,1314417,-,1309158,"0,40 %",05259,21:07:00
24,NaN,GBP/EUR,11426,-,11431,"-0,05 %",-00006,21:06:00
25,NaN,GBP/CHF,12041,-,12036,"0,04 %",00005,21:06:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,12041,-,12036,"0,04 %",00005,21:06:00
28,NaN,EUR/CHF,10541,-,10527,"0,14 %",00015,21:06:00
29,NaN,JPY/CHF (100:1),09200,-,09200,"-0,34 %",00000,21:06:00
30,NaN,USD/CHF,09734,-,09753,"-0,19 %",-00019,21:06:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,290258,-,290261,"0,00 %",-00003,21:07:00
33,NaN,USD/UAH,268050,-,268897,"-0,32 %",-00847,21:05:00
34,NaN,CHF/UAH,275347,-,275792,"-0,16 %",-00445,21:07:00
35,NaN,GBP/UAH,331551,-,331846,"-0,09 %",-00295,21:07:00

**Ссылка 3**

In [40]:
data = pd.read_html('https://www.finam.ru/quotes/currencies/')
# len(data)
data[0]

,Unnamed: 0,Инструмент,Посл. сделка,% Изм. цены,Открытие,Макс.,Мин.,Закрытие,"Объем, шт.",Время обн.
0,NaN,Eur/Chf,1.0538 CHF,0.12%,1.0525,1.0542,1.0525,1.052500,NaN,07.05 21:17
1,NaN,Eur/Jpy,115.077 JPY,0.51%,114.4760,115.1000,114.4650,114.490000,NaN,07.05 21:17
2,NaN,Eur/Usd,1.0829 $,0.32%,1.0795,1.0834,1.0767,1.079400,NaN,07.05 21:17
3,NaN,Usd/Chf,0.9732 CHF,-0.17%,0.9748,0.9784,0.9729,0.974900,NaN,07.05 21:17
4,NaN,Gbp/Usd,1.2376 $,0.28%,1.2341,1.2419,1.2266,1.234200,NaN,07.05 21:17
5,NaN,Usd/Jpy,106.28 JPY,0.2%,106.0500,106.6600,105.9900,106.070000,NaN,07.05 21:17
6,NaN,Usd/Cad,1.3969 CAD,-1.27%,1.4150,1.4173,1.3953,1.414800,NaN,07.05 21:17
7,NaN,Aud/Nzd,1.067 NZD,0.29%,1.0640,1.0699,1.0635,1.063900,NaN,07.05 21:17
8,NaN,Индекс доллара*,99.86 $,-0.28%,100.2700,100.4600,99.8300,100.140000,NaN,07.05 21:17
9,NaN,Aud/Usd,0.6496 $,1.58%,0.6396,0.6506,0.6379,0.639500,NaN,07.05 21:17
10,NaN,AMDRUB курс ЦБ,0.15,0.01%,NaN,NaN,NaN,0.150000,NaN,07.05 00:00
11,NaN,Aud/Cad,0.9073 CAD,0.23%,0.9048,0.9125,0.9040,0.905200,NaN,07.05 21:17
12,NaN,Aud/Chf,0.6321 CHF,1.38%,0.6235,0.6342,0.6220,0.623500,NaN,07.05 21:17
13,NaN,Aud/Dkk,4.4753 DKK,1.31%,4.4198,4.4904,4.4089,4.417600,NaN,07.05 21:17
14,NaN,Aud/Jpy,69.04 JPY,1.76%,67.8300,69.1570,67.6340,67.844000,NaN,07.05 21:17
15,NaN,Aud/Nok,6.6429 NOK,1.11%,6.5811,6.6633,6.5554,6.570200,NaN,07.05 21:17
16,NaN,Aud/Sek,6.3626 SEK,1.16%,6.2959,6.3851,6.2874,6.289600,NaN,07.05 21:17
17,NaN,Aud/Sgd,0.9184 SGD,1.03%,0.9092,0.9203,0.9075,0.909000,NaN,07.05 21:17
18,NaN,AUDRUB курс ЦБ,47.52,0%,NaN,NaN,NaN,47.580000,NaN,07.05 00:00
19,NaN,AZNRUB курс ЦБ,43.24,0.01%,NaN,NaN,NaN,42.870000,NaN,07.05 00:00
20,NaN,BCH-USD,252.9 $,NaN,NaN,NaN,NaN,246.490000,NaN,07.05 21:17
21,NaN,BGNRUB курс ЦБ,40.82,0.01%,NaN,NaN,NaN,40.440000,NaN,07.05 00:00
22,NaN,Bitcoin / Euro,9048.37,NaN,NaN,NaN,NaN,8587.270000,NaN,07.05 21:17
23,NaN,Bitcoin / U.S. dollar,9781.32,NaN,NaN,NaN,NaN,9253.290000,NaN,07.05 21:17
24,NaN,Bitcoin Cash / Bitcoin,0.02577714,NaN,NaN,NaN,NaN,0.026681,NaN,07.05 21:17
25,NaN,Bitcoin Cash / Euro,233.84,NaN,NaN,NaN,NaN,228.550000,NaN,07.05 21:17
26,NaN,Bitcoin Cash / U.S. dollar,248.01,NaN,NaN,NaN,NaN,246.580000,NaN,05.05 01:00
27,NaN,BKTRUB_TOM,39.26 ₽,0.41%,NaN,NaN,NaN,39.260000,NaN,25.06.14 18:36
28,NaN,BRLRUB курс ЦБ,13.26,-0.03%,NaN,NaN,NaN,13.630000,NaN,07.05 00:00
29,NaN,BTC-EUR,9046.9 €,NaN,NaN,NaN,NaN,8582.130000,NaN,07.05 21:17